### ISSUE TITLE
can't delete builds

### ISSUE THREAD

**Issue by vitriolix** [fl33tcode/fl33t-tools#1]
When I click on a build's trashcan icon to delete it from a train, nothing happens for a few seconds, then eventually I see this in the js console:

2VM727:1 DELETE https://api.fl33t.com/team/DQ/build/J8dg 504
(anonymous) @ VM727:1
o @ api.js:56
onClick @ index.js:315
a @ react-dom.production.min.js:15
invokeGuardedCallback @ react-dom.production.min.js:16
invokeGuardedCallbackAndCatchFirstError @ react-dom.production.min.js:16
u @ react-dom.production.min.js:20
p @ react-dom.production.min.js:22
m @ react-dom.production.min.js:22
d @ react-dom.production.min.js:21
g @ react-dom.production.min.js:24
y @ react-dom.production.min.js:24
Be @ react-dom.production.min.js:88
vr @ react-dom.production.min.js:222
J @ react-dom.production.min.js:44
He @ react-dom.production.min.js:89
br @ react-dom.production.min.js:223
We @ react-dom.production.min.js:89
builds:1 Access to fetch at 'https://api.fl33t.com/team/DQ/build/J8dg' from origin 'https://www.fl33t.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
builds:1 Uncaught (in promise) TypeError: Failed to fetch

**Comment by mrshoe** [comment]
This request was taking too long and timing out, due to some bookkeeping on the backend during the build deletion. Fixed it.
